<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="wwwroot\icons\**" />
    <Content Remove="wwwroot\icons\**" />
    <EmbeddedResource Remove="wwwroot\icons\**" />
    <None Remove="wwwroot\icons\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ETCS.PaymentGateway\ETCS.PaymentGateway.csproj" />
    <ProjectReference Include="..\ETCS.Shared\ETCS.Shared.csproj" />
  </ItemGroup>

</Project>
