//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
// 
#pragma warning disable 1591

namespace AVISoap.AVISoapWebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="iBonusPOS", Namespace="posServer")]
    public partial class iBonusPOS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback posServiceRoutineOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public iBonusPOS() {
            this.Url = "http://127.0.0.1:18083";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event posServiceRoutineCompletedEventHandler posServiceRoutineCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="posServer", ResponseNamespace="posServer", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("posResult", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SOAPPOSResultResponse posServiceRoutine([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] SOAPPOSRequest posRequest, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] Items items) {
            object[] results = this.Invoke("posServiceRoutine", new object[] {
                        posRequest,
                        items});
            return ((SOAPPOSResultResponse)(results[0]));
        }
        
        /// <remarks/>
        public void posServiceRoutineAsync(SOAPPOSRequest posRequest, Items items) {
            this.posServiceRoutineAsync(posRequest, items, null);
        }
        
        /// <remarks/>
        public void posServiceRoutineAsync(SOAPPOSRequest posRequest, Items items, object userState) {
            if ((this.posServiceRoutineOperationCompleted == null)) {
                this.posServiceRoutineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnposServiceRoutineOperationCompleted);
            }
            this.InvokeAsync("posServiceRoutine", new object[] {
                        posRequest,
                        items}, this.posServiceRoutineOperationCompleted, userState);
        }
        
        private void OnposServiceRoutineOperationCompleted(object arg) {
            if ((this.posServiceRoutineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.posServiceRoutineCompleted(this, new posServiceRoutineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="posServer")]
    public partial class SOAPPOSRequest {
        
        private ushort versionField;
        
        private ushort posTypeField;
        
        private string transactionIDField;
        
        private ushort sequenceNoField;

        private uint amountCNField;
        
        private uint quickReloadCNField;
        
        private uint cardIDField;
        
        private uint bonusPointField;
        
        private string customerIDField;
        
        private uint dobField;
        
        private uint staffIDField;
        
        private ushort refCodeField;
        
        private string descriptionField;
        
        private string challengeField;
        
        private string terminalSNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ushort version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ushort posType {
            get {
                return this.posTypeField;
            }
            set {
                this.posTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string transactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ushort sequenceNo {
            get {
                return this.sequenceNoField;
            }
            set {
                this.sequenceNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public uint amountCN
        {
            get {
                return this.amountCNField;
            }
            set {
                this.amountCNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public uint quickReloadCN {
            get {
                return this.quickReloadCNField;
            }
            set {
                this.quickReloadCNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public uint cardID {
            get {
                return this.cardIDField;
            }
            set {
                this.cardIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public uint bonusPoint {
            get {
                return this.bonusPointField;
            }
            set {
                this.bonusPointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string customerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public uint dob {
            get {
                return this.dobField;
            }
            set {
                this.dobField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public uint staffID {
            get {
                return this.staffIDField;
            }
            set {
                this.staffIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ushort refCode {
            get {
                return this.refCodeField;
            }
            set {
                this.refCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string challenge {
            get {
                return this.challengeField;
            }
            set {
                this.challengeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string terminalSN {
            get {
                return this.terminalSNField;
            }
            set {
                this.terminalSNField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="posServer")]
    public partial class SOAPPOSResult {
        
        private ushort posResultField;
        
        private ushort sequenceNoField;
        
        private uint cardIDField;
        
        private string customerIDField;
        
        private uint balPrepaidCNField;
        
        private uint balBonusField;
        
        private uint amountPrepaidCNField;
        
        private uint amountBonusField;
        
        private ulong accSpendingCNField;
        
        private uint quickReloadCNField;
        
        private ulong dobField;
        
        private uint expiryDateField;
        
        private uint insufficientCNField;
        
        private ushort refCodeField;
        
        private ulong cardSNField;
        
        private uint branchCodeField;
        
        private uint terminalCodeField;
        
        private uint staffIDField;
        
        private string replyChallengeField;
        
        private string terminalSNField;
        
        private uint dwCat1BalField;
        
        private uint dwCat1ExpiryField;
        
        private uint dwCat2BalField;
        
        private uint dwCat2ExpiryField;
        
        private uint dwCat3BalField;
        
        private uint dwCat3ExpiryField;
        
        private uint dwCat4BalField;
        
        private uint dwCat4ExpiryField;
        
        private uint dwCat5BalField;
        
        private uint dwCat5ExpiryField;
        
        private uint dwCat6BalField;
        
        private uint dwCat6ExpiryField;
        
        private uint dwCat7BalField;
        
        private uint dwCat7ExpiryField;
        
        private uint dwCat8BalField;
        
        private uint dwCat8ExpiryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ushort posResult {
            get {
                return this.posResultField;
            }
            set {
                this.posResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ushort sequenceNo {
            get {
                return this.sequenceNoField;
            }
            set {
                this.sequenceNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public uint cardID {
            get {
                return this.cardIDField;
            }
            set {
                this.cardIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string customerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public uint balPrepaidCN {
            get {
                return this.balPrepaidCNField;
            }
            set {
                this.balPrepaidCNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public uint balBonus {
            get {
                return this.balBonusField;
            }
            set {
                this.balBonusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public uint amountPrepaidCN {
            get {
                return this.amountPrepaidCNField;
            }
            set {
                this.amountPrepaidCNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public uint amountBonus {
            get {
                return this.amountBonusField;
            }
            set {
                this.amountBonusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ulong accSpendingCN {
            get {
                return this.accSpendingCNField;
            }
            set {
                this.accSpendingCNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public uint quickReloadCN {
            get {
                return this.quickReloadCNField;
            }
            set {
                this.quickReloadCNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ulong dob {
            get {
                return this.dobField;
            }
            set {
                this.dobField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public uint expiryDate {
            get {
                return this.expiryDateField;
            }
            set {
                this.expiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public uint insufficientCN {
            get {
                return this.insufficientCNField;
            }
            set {
                this.insufficientCNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ushort refCode {
            get {
                return this.refCodeField;
            }
            set {
                this.refCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ulong cardSN {
            get {
                return this.cardSNField;
            }
            set {
                this.cardSNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public uint branchCode {
            get {
                return this.branchCodeField;
            }
            set {
                this.branchCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public uint terminalCode {
            get {
                return this.terminalCodeField;
            }
            set {
                this.terminalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public uint staffID {
            get {
                return this.staffIDField;
            }
            set {
                this.staffIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string replyChallenge {
            get {
                return this.replyChallengeField;
            }
            set {
                this.replyChallengeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string terminalSN {
            get {
                return this.terminalSNField;
            }
            set {
                this.terminalSNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public uint dwCat1Bal {
            get {
                return this.dwCat1BalField;
            }
            set {
                this.dwCat1BalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public uint dwCat1Expiry {
            get {
                return this.dwCat1ExpiryField;
            }
            set {
                this.dwCat1ExpiryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public uint dwCat2Bal {
            get {
                return this.dwCat2BalField;
            }
            set {
                this.dwCat2BalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public uint dwCat2Expiry {
            get {
                return this.dwCat2ExpiryField;
            }
            set {
                this.dwCat2ExpiryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public uint dwCat3Bal {
            get {
                return this.dwCat3BalField;
            }
            set {
                this.dwCat3BalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public uint dwCat3Expiry {
            get {
                return this.dwCat3ExpiryField;
            }
            set {
                this.dwCat3ExpiryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public uint dwCat4Bal {
            get {
                return this.dwCat4BalField;
            }
            set {
                this.dwCat4BalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public uint dwCat4Expiry {
            get {
                return this.dwCat4ExpiryField;
            }
            set {
                this.dwCat4ExpiryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public uint dwCat5Bal {
            get {
                return this.dwCat5BalField;
            }
            set {
                this.dwCat5BalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public uint dwCat5Expiry {
            get {
                return this.dwCat5ExpiryField;
            }
            set {
                this.dwCat5ExpiryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public uint dwCat6Bal {
            get {
                return this.dwCat6BalField;
            }
            set {
                this.dwCat6BalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public uint dwCat6Expiry {
            get {
                return this.dwCat6ExpiryField;
            }
            set {
                this.dwCat6ExpiryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public uint dwCat7Bal {
            get {
                return this.dwCat7BalField;
            }
            set {
                this.dwCat7BalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public uint dwCat7Expiry {
            get {
                return this.dwCat7ExpiryField;
            }
            set {
                this.dwCat7ExpiryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public uint dwCat8Bal {
            get {
                return this.dwCat8BalField;
            }
            set {
                this.dwCat8BalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public uint dwCat8Expiry {
            get {
                return this.dwCat8ExpiryField;
            }
            set {
                this.dwCat8ExpiryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="posServer")]
    public partial class SOAPPOSResultResponse {
        
        private SOAPPOSResult returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public SOAPPOSResult @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="posServer")]
    public partial class Item {
        
        private string descriptionField;
        
        private uint amountBonusField;
        
        private bool amountBonusFieldSpecified;
        
        private uint balPrepaidCNField;
        
        private bool balPrepaidCNFieldSpecified;
        
        private ushort quantityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public uint amountBonus {
            get {
                return this.amountBonusField;
            }
            set {
                this.amountBonusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool amountBonusSpecified {
            get {
                return this.amountBonusFieldSpecified;
            }
            set {
                this.amountBonusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public uint balPrepaidCN {
            get {
                return this.balPrepaidCNField;
            }
            set {
                this.balPrepaidCNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool balPrepaidCNSpecified {
            get {
                return this.balPrepaidCNFieldSpecified;
            }
            set {
                this.balPrepaidCNFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ushort quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="posServer")]
    public partial class Items {
        
        private Item[] productItemsField;
        
        private int itemCountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("productItems", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public Item[] productItems {
            get {
                return this.productItemsField;
            }
            set {
                this.productItemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int itemCount {
            get {
                return this.itemCountField;
            }
            set {
                this.itemCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void posServiceRoutineCompletedEventHandler(object sender, posServiceRoutineCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class posServiceRoutineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal posServiceRoutineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SOAPPOSResultResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SOAPPOSResultResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591